project:
  type: book
  output-dir: .

book:
  title: "Handling Missing Data in Multilevel Models with Few Clusters: A Simulation Study"
  date: "Submission date: May 05, 2026"
  author:
    name: Lona Frießner
  downloads: [pdf]
  abstract: "Multilevel studies often involve two challenges simultaneously: small numbers of clusters and missing data. However, the performance of modern missing-data methods under these combined conditions remains insufficiently understood, particularly in models with missing predictor variables and contextual effects. This thesis examines the performance of multiple imputation, using both conventional and small-sample-corrected degrees of freedom, and compares it with a fully Bayesian approach in a simulation study. The study features a simple random-intercept model with a manifest group-mean predictor, with missings in the predictor variable and one level-2 auxiliary variable. Simulation conditions varied in terms of intraclass correlation (.1 vs. .3), missingness mechanism (MAR vs. MCAR), between-group effect size (0 vs. 0.4), and level-2 sample size (15, 30, 60).  Method performance was evaluated in terms of bias, coverage, standard deviation of point estimates, and interval width. Results indicate a trade-off between bias and interval width for the between-group effect: multiple imputation tended to produce more biased estimates, particularly under low intraclass correlation conditions, whereas the Bayesian approach yielded wider credible intervals. As coverage under conventional degrees of freedom was already close to the nominal level, the small-sample correction tended to result in overcoverage. The findings are discussed with regard to methodological limitations and their implications for applied multilevel research."
  chapters:
    - index.qmd
    - chapters/theory.qmd
    - chapters/methods.qmd
    - chapters/results.qmd
    - chapters/discussion.qmd
    - references.qmd
  appendices:
    - appendices/AppendixA.qmd
    - appendices/convergence.qmd
    - appendices/AppendixB.qmd
    - appendices/AppendixC.qmd

  repo-url: https://github.com/lonalytical/masterthesis
  search: true

thesis:
  supervisor: 
    - name: Prof. Dr. Simon Grund 
    - name: Mark Lustig
  degree-name: Master of Science
  university: University of Hamburg
  department: Quantitative Methods
  group: Institute of Psychology
  faculty: Faculty of Psychology and Human Movement Science
  #declaration: "frontmatter/declaration.tex"
  #quotation:
  #  text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
  #  attribution: Dave Barry
  #acknowledgements: "frontmatter/acknowledgements.tex"
  #abbreviations: "frontmatter/abbreviations.tex"
  #symbols: "frontmatter/symbols.tex"
  #dedication: "frontmatter/dedication.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [bibliography.bib]
csl: apa.csl

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf:
    urlcolor: blue
    toclinkcolor: black
    toc-depth: 2
    classoption:
      - 11pt
      - english
      - singlespacing
      - headsepline
      - openany
    link-citations: true
    include-in-header:
      text: |
        \usepackage{enumitem}
        \setlist[itemize]{label=--}
        \usepackage{tabularx}
        \renewcommand{\arraystretch}{1.2}
        \captionsetup{width=\textwidth}
    include-after-body: 
        - "backmatter/eid.tex"
        - "backmatter/gAI.tex"
        
    
