---
title: "Methods"
editor: 
  markdown: 
    wrap: 72
---

A simulation study was conducted in order to compare the performance of
methods for missing data handling in small-sample multilevel random
intercept models.\
The idea behind a simulation study is to carry out a computer experiment
[@morris], where data with known
characteristics is simulated and subsequently analyzed with the methods
of interest. The analysis results can be compared to the truth, allowing
for assessment of the performance of the methods
[@siepe].

Planning of the simulation study followed the ADEMP structure proposed
by Siepe et al. [-@siepe] and will be
reported based on their guidelines.

## Data generation mechanism

### Data-generating model

The data-generating model is a two-level random intercept model: $$
\begin{aligned}
Y_{ij} =\gamma_{10} (X_{ij} - \bar{X.}_j) +\gamma_{01} \bar{X.}_j + \gamma_{02} W_j + u_{0j} + e_{ij} 
\end{aligned}
$$ {#eq-dgm}

$Y_{ij}$, $X_{ij}$ and $W_{j}$ are parameterized to have a mean of zero
and a variance of 1 on the population level.\
First, between- and within-components of $X_{ij}$ were simulated,
independent of each other and with variances chosen to achieve a
prespecified intraclass coefficient (see @sec-factors): $$ 
X_{ij} = u_{Xj} + e_{Xij},
$$ $$
u_{X_j}\sim N(0,{\tau_x}^2), \qquad e_{X_{ij}}\sim N(0,{\sigma_x}^2) 
$$ with ${\tau_x}^2 = ICC_x$ and ${\sigma_x}^2 = 1 - ICC_x$,
respectively.\
$X_{ij}$ was then group-mean-centered.\
The group-level covariate $W_{j}$ was constructed with a linear
regression equation to have a prespecified correlation with $\bar{X.}_j$
($\rho_{\bar{X}W}$):
$$ W_j=a\bar{X}_j + e_{Wj}, \qquad e_{Wj}\sim N(0,{\sigma_w}^2)  $$ The
residual variance ${\sigma_w}^2$ and the regression coefficient $a$ are
fully determined by the restriction that $Var(W_j) = 1$: $$
\begin{aligned}
{\sigma_w}^2 = 1- \rho_{\bar{X}W}^2, \\
a =\frac{\rho_{\bar{X}W}}{\sqrt{\tau_x^2+ \frac{{\sigma_x}^2 }{n} }}
\end{aligned}
$$

Finally, the random effects on the group and the individual level were
generated as $$u_{0j}\sim N(0,\psi^2), \qquad e_{ij}\sim N(0,\sigma^2)$$
and independent of each other.\
Individual and group residual variances of $Y_{ij}$ are determined by
the constraints of a prespecified residual $ICC$ of $Y_{ij}$,
$Var(Y_{ij}) = 1$ and $Var(X_{ij}) = 1$[^methods-1]:
$$ \psi^2 = ICC_{Y|X,W} \cdot (1-{{\gamma_{10}}^2(\sigma_X^2- \frac{\sigma_X^2}{n_j})+{\gamma_{01}}^2(\tau_x^2+\frac{\sigma_X^2 }{n_j}) } $$
$$
\begin{aligned}
\sigma^2 = (1 - ICC_{Y|X,W}) \cdot (1-{{\gamma_{10}}^2(\sigma_X^2- \frac{\sigma_X^2 }{n_j})+{\gamma_{01}}^2(\tau_x^2+\frac{\sigma_X^2 }{n_j}) }
\end{aligned}
$$ The full derivation of these equations is provided in @sec-appA.

[^methods-1]: as well as setting $\gamma_{02}$ to be zero across all
    conditions, see @sec-factors

### Missing data generation

After simulation of the complete dataset, values of the $X$-variable
have been deleted to simulate missingness. A 'missingness tendency' $r$ was simulated for each $X$-value according to 
$$ 
\begin{aligned}
r_{ij}=\alpha+\beta W_j+e_{ij}, \qquad e_{ij}\sim N(0,1-\beta^2)
\end{aligned}
$$ 
$r_{ij}$ is normally distributed. Observations with $r_{ij} > 0$ were set to missing.\
The intercept $\alpha$ controls the proportion of missingness in $X$,
whereas the slope $\beta$ determines the strength of the
missing-at-random mechanism. When $\beta = 0$, missingness is completely
at random (MCAR). With increasing $\beta$, the missingness mechanism
becomes more dependent on the $W$-values; with $\beta = 1$, missingness
would be completely deterministic.  
For the present simulation, $\beta = 0.3$ was used for MAR conditions, corresponding to approximately $9\%$ explained variance.

### Factors of the data-generating mechanism {#sec-factors}

A summary of simulation conditions is provided in @tbl-sim-settings. 
```{r, results='asis', echo=FALSE, message=FALSE}
#| label: tbl-sim-settings
#| tbl-cap: "Simulation conditions for the Data-Generating Model and the Generation of Missing Values"
library(dplyr)
library(knitr)
library(kableExtra)
tab.cond <- data.frame(
  Parameter = c(
    "$N_1$", "$N_2$", "ICC of $X$ and $Y$", "Correlation $\\bar{X}W$",
    "Effect of $(X_{ij}-\\bar{X}_{.j})$", "Effect of $\\bar{X}_{.j}$", "Effect of $W_j$", "Pattern", "Mechanism", "Proportion"
  ),
  
  Value = c(
    "10",
    "15 / 30 / 60",
    ".1 / .3",
    ".3",
    ".2",
    "0 / .4",
    "0",
    "$X \\sim W$",
    "MCAR / MAR",
    ".3"
  )
)

kable(tab.cond, 
      format = "latex",
      escape = FALSE, 
      booktabs = TRUE,
      col.names = NULL, 
      align = c("l","l")
) %>%
  kable_styling(
    font_size = 8,
    full_width = FALSE,
    position = "center", 
    latex_options = c("hold_position")) %>%
  pack_rows(index = c("Data conditions" = 4, "Model parameters" = 3, "Missing values" = 3)
)
```
The number of Level-2 units was manipulated across conditions ($N_2 = 15, 30, 60$), while the number of Level-1 observations was kept constant ($N_1 = 10$). 
The between-cluster effect of $\bar{X}_{.j}$ was varied ($\gamma_{01} = 0, .40$), whereas the within-cluster effect of ($X_{ij}-\bar{X}_{.j}$) was held constant at $.20$ and the effect of $W_{j}$ was set to zero. This results in conditions with either a negative and a positive context effect (i.e., $\gamma_{10} - \gamma_{01}$) of $X$ in the population model.
The ICC of $X$ and the residual ICC of $Y$ were varied ($\rho_X = \rho_{Y|X} = .10, .30$). Missing data were generated on X with a varying missingness mechanism (MCAR or MAR with a strength of $\beta = .30$), with a constant missingness rate of $30 \%$.
The factors were combined fully factorial, creating $3 \times 2 \times 2 \times 2 = 24$ conditions.  
All in all, these settings reflect a number of the typical applications in cross-sectional and longitudinal applied research (e.g., smaller and larger intraclass correlation coefficients (ICC) and level-two sample sizes). They also create sufficient methodological variation to evaluate the properties of the methods of interest (e.g., null versus substantial effects).



## Estimands of the focal analysis model
The focal analysis model is
$$
\begin{aligned}
Y_{ij} =\gamma_{10} (X_{ij} - \bar{X.}_j) +\gamma_{01} \bar{X.}_j + u_{0j} + e_{ij} 
\end{aligned}
$$ {#eq-fam}

The primary target is the Level-2-effect, $\gamma_{01}$. Additionally, the Level-1-effect $\gamma_{10}$ was evaluated.

## Methods of Missing Data Handling
Four methods will be compared, alongside the benchmark analysis of Complete Data (CD).

### Listwise Deletion (LD)
Listwise Deletion was used as a standard reference method for missing data handling. Cases with missing $X$-values were excluded prior to analysis. The group means $\bar{X}_{.j}$ were then calculated only from the remaining observations. Then, group-mean centering was applied.

### Multiple Imputation (MI) with standard (MI-R) and adjusted (MI-a) degrees of freedom
For both multiple imputation methods, a joint modeling approach was employed. Although only values in $X$ were missing, the multivariate specification preserves the multilevel structure during imputation. The multivariate empty model is generally suitable for random-intercep models [@grundMI16]:
$$
\left(\begin{matrix}Y_{ij}\\X_{ij}\\W_j\\\end{matrix}\right)=\left(\begin{matrix}\beta_{0Y}\\\beta_{0X}\\\beta_{0W}\\\end{matrix}\right)+\left(\begin{matrix}u_{Yj}\\u_{Xj}\\u_{Wj}\\\end{matrix}\right)+\left(\begin{matrix}e_{Yij}\\e_{Xij}\\0\\\end{matrix}\right)
$$
The random effects $(u_{Yj}, u_{Xj}, u_{Wj})^{\top}$ and the residuals $(e_{Yij}, e_{Xij})^{\top}$ follow multivariate normal distributions with mean zero and covariance matrices $\Psi=\left[\ \begin{matrix}\psi_y^2&\psi_{yx}&\psi_{yw}\\\psi_{yx}&\psi_x^2&\psi_{xw}\\\psi_{yw}&\psi_{xw}&\psi_w^2\\\end{matrix}\right]$ and $\Sigma=\left[\ \begin{matrix}\sigma_y^2&\sigma_{yx}\\\sigma_{yx}&\sigma_x^2\\\end{matrix}\ \right]$

$W_j$ serves as an auxiliary variable to explain missingness.  
Imputation was executed with the R package `jomo` [@quartagnoJomoPackageMultilevel2023] with 2000 burn-in-iterations and 3000 post-burn-in iterations, saving every 300th imputation (10 imputations).  
For MI-R, degrees of freedom for calculating the test statistic were calculated with the software standard (Rubin´s rules, assuming infinite degrees of freedom in complete data).  
For MI-a, degrees of freedom were calculated with $df_{\gamma_{10}} = M - r - 1$ ($M$: total number of Level-1 units; $r$: total number of predictors, in the present case $2$) and $df_{\gamma_{01}} = N_2 - q - 1$ ($N_2$: number of Level-2 units; $q$: number of Level-2 predictors, here: $1$)

### Fully Bayesian Analysis
A factored regression specification was used within the Bayesian framework to allow the inclusion of the auxiliary variable $W$ while leaving the focal analysis model unchanged:
$$ 
g\left(y,\ x,w;\gamma\right)=g_w\left(w\middle| y,x;\gamma_w\right)\ \times\ g_y\left(y\middle| x;\gamma_y\right)\ \times\ g_x(x;\gamma_x)\ 
$$ {#eq-frs}

Here, $g_w$ is the conditional distribution of the auxiliary variable, while $g_y$ corresponds to the substantive analysis model.  
The burn-in period was set to 1000 iterations, followed by 3000 post-burn-in iterations. The model was estimated using the package `mdmb` [@mdmb] with its default noninformative priors.

### Extracted quantities

For complete data, listwise deletion and both multiple imputation methods, point estimates of $\gamma_{10}$ and $\gamma_{01}$ as well as their standard errors and 95$\%$ - confidence intervals were extracted.  
For the fully Bayesian method, the posterior means of $\gamma_{10}$ and $\gamma_{01}$ were used as point estimates along with posterior standard deviations and 95$\%$ credible intervals. For comparability with the frequentist approaches and in line with common simulation practice, these posterior summaries were treated analogously to frequentist estimates and intervals [@morris].

## Performance measures

Three performance measures were used for each parameter ($\gamma_{10}$ and $\gamma_{01}$):

1. Bias of point estimates, defined as the difference between the parameter´s mean estimated and true value.
1. Coverage of confidence/credible intervals, defined as the proportion of simulation repetitions that captured the true parameter value inside the CI.
1. Standard deviation of the estimations across simulation repetitions.

Monte Carlo uncertainty of the estimated performance measures was calculated using Monte Carlo Standard Errors (MCSE), using the formulas provided in Siepe et al. [-@siepe].  
For each condition, 1000 simulation replications were used, based on comparable simulation studies [@grundMI18; @enders16] and ensuring a sufficiently small MCSE of < 1% for coverage ^[MCSE calculation for bias and standard deviation are based on the sample variance of the estimates and cannot be pre-calculated.].  

The simulation was conducted in RStudio with the aim of full reproducibility, following guidelines of the repro book (ZITIEREN), e.g. by setting a seed for simulation and using reproducible package environments. The code and all relevant information for reproduction can be found in the digital version of the master thesis. (*LINK*)    



INSGESAMT NOCH MEHR BESCHREIBEN? ALSO AUCH, WELCHE GEDANKEN ICH MIR ZUR AUSWERTUNG GEMACHT HATTE..?
(z.B., wie  Performance measures evaluiert werden sollen)

ERKLÄRUNG DER METHODEN KOMMT SCHON IM THEORIETEIL, WÜRDE ICH SAGEN