---
title: "Theory"
---

## Theoretical foundation of multilevel models
::: {.callout-tip icon=false}

### Example

Imagine you are interested in the musical self-concept of young adults and whether it is related to how many hours they practice their instrument each week.

To investigate this question, you collect data from several youth ensembles. You recruit 15 ensembles, each consisting of approximately 10 players. Every player completes a questionnaire assessing their musical self-concept as well as their weekly practice time.  
At first glance, this seems like a simple dataset of 150 individuals. But is it really that simple?  
Players from the same ensemble rehearse together, share teachers, and experience similar social and musical environments. Their responses may therefore be more similar within ensembles than between ensembles.
:::

Populations like this, where units of interest (e.g., music players, students, employees) are grouped into higher-level units (e.g., ensembles, classes, firms), are common in the human social life and therefore in psychological studies.  
The resulting data is called *nested* or *clustered* [@snijders, p. 7].  
From a sampling perspective, a so-called *multistage sampling process* (sample groups first, then individuals inside these groups^[In this thesis, the term 'groups' refers to the higher-level units of the data and level-1 units are referred to as 'persons'. However, it is important to note that these models can also be used for longitudinal research, where measurement points are on level 1 and individuals are the level-2 units. Furthermore, more than two levels are also possible, but are not discussed here.]) is not independent: After selecting a group, you will try to sample all of the members of this group, making it more likely to select one person in this group over others in non-selected groups [@snijders, p. 7].  More importantly, individuals inside the same group typically share contextual influences (e.g., the same ensemble teacher, the same class room) and thus will give more similar responses in surveys and behavior. As a consequence, the basic assumption of independence in traditional linear modeling is violated, because error terms will be correlated [@raudenbush, p. xx].  
One well-suited and popular possibility to account for this fact is the use of *multilevel models* (also called *hierarchical linear models* or *mixed models*).  


### The concept of multilevel regression models
The aim of regression analysis, whether single- or multilevel, is to explain variance in an outcome variable by including associated variables in the model as predictors [@snijders, p. 80]. In single-level regression, the residual $e_{i}$ captures the *unexplained variance* in $Y$, that is differences in the outcome from the prediction that the model made [@leonhart, p. 319]. The assumption of the classical linear model is that after inclusion of all *systematic* influences on $Y$, the residuals are *random*. Specifically, they are assumed to have expectation zero ($E(e_i)=0$), constant variance across observations (homoscedasticity; $Var(e_i)=\sigma^2$), and to be independent across observations ($Cov(e_i, e_{i'})=0$ for $i \neq i'$) [@fahrmeir, p.87].  

Multilevel models (MLM) extend regular linear regression by adding level-2 *random effects* to explain the variability between groups that cannot be accounted for by predictors [@snijders, p. 80]. This partition of variance can be expressed in the multilevel regression model without predictors, the *empty model*:

$$
Y_{ij} = \gamma_{00} + u_{0j} + e_{ij}
$$
Here, the outcome value of person $i$ in group $j$ is modeled as the sum of the overall mean $\gamma_{00}$, a group level random effect $u_{0j}$ and a random effect on the individual level, $e_{ij}$ [@snijders, p. 49]. The random intercept $u_{0j}$ captures the dependency of individuals within one group statistically, as all individuals in group $j$ have the same $u_{0j}$ value and their outcome values are therefore correlated. Conditional on this group component, however, the remaining level-1 residuals $e_{ij}$ are assumed to be independent, addressing the issue of dependency that would arise if a single-level regression model were applied to nested data.

### Within- and between- group regressions and inclusion of predictors

Predictors can then be included to explain variability within groups (level 1) and between groups (level 2).  
**At level 1**, the outcome of a person $i$ in group $j$ is modeled as a function of individual-level explanatory variables $X_{ij}$ to obtain the within-group regression model. For simplicity, the model is illustrated with a single level-1 predictor:

$$
Y_{ij} =  \beta_{0j} + \beta_{1j}X_{ij} + e_{ij}
$$ {#eq-mlm}

**At level 2**, the variation between groups in the group-dependent coefficients $\beta_{0j}$ and $\beta_{1j}$ is modeled. Each group may have its own intercept and slope. These coefficients can be separated into a fixed part (the average coefficient across groups) and a random deviation from this average [@snijders, p. 75]. Without level-2 predictors:
$$
\beta_{0j}
=
\underbrace{\gamma_{00}}_{\text{Fixed part}}
+
\underbrace{u_{0j}}_{\text{Random part}}
$$
$$
\beta_{1j}
=
\underbrace{\gamma_{10}}_{\text{Fixed part}}
+
\underbrace{u_{1j}}_{\text{Random part}}
$$
On this level, in order to explain between-group variability in the intercepts and slopes, level-2 predictors $Z_j$ may be included [@snijders, p. 80]. Including such predictors may reduce the unexplained variance of the random effects $u_{0j}$ and $u_{1j}$. With a single level-2 predictor, the model becomes:

$$
\beta_{0j}
=
\gamma_{00} + \gamma_{01}Z_{j}
+
u_{0j}
$$ {#eq-beta0j}

$$
\beta_{1j}
=
\gamma_{10} + \gamma_{11}Z_{j}
+
u_{1j}
$$ {#eq-beta1j}

Substituting the level-2 equations @eq-beta0j and @eq-beta1j into the level-1 model @eq-mlm yields the combined multilevel model:

$$
Y_{ij} =
\underbrace{\gamma_{00} + \gamma_{10}X_{ij} + \gamma_{01}Z_{j} + \gamma_{11}X_{ij}Z_{j}}_{\text{Fixed part}}
+
\underbrace{u_{0j} + u_{1j}X_{ij} + e_{ij}}_{\text{Random part}}
$$
$Y_{ij}$: Outcome for individual $i$ in group $j$  
$X_{ij}$: Level-1 (within-group) predictor  
$Z_j$: Level-2 (between-group) predictor  

$\gamma_{00}$: Fixed intercept (overall mean when $X_{ij}=0$, $Z_j=0$)  
$\gamma_{10}$: Average within-group effect of $X_{ij}$ on $Y_{ij}$  
$\gamma_{01}$: Effect of $Z_j$ on the intercept (between-group effect)  
$\gamma_{11}$: Cross-level interaction; change in the effect of $X_{ij}$ depending on $Z_j$  

$u_{0j}$: Random intercept (group-specific deviation from $\gamma_{00}$)  
$u_{1j}$: Random slope (group-specific deviation from $\gamma_{10}$)  
$e_{ij}$: Level-1 residual

If no level-2 predictors are included ($Z_j = 0$), the model reduces to the simpler random-coefficients model without contextual predictors.

### Distributional assumptions of the multilevel regression model

Similar distributional assumptions are made for the level-2 random effects as for the residuals in single-level regression: they have mean zero, constant variances across groups, and are independent across clusters and independent of the level-1 residuals. However, random effects within the same cluster may be correlated and are often expected to do so [@snijders, p. 76]. Additionally, residuals and random effects are commonly assumed to follow a normal distribution for convenience, as it facilitates the likelihood-based estimation of the unknown parameters [@fahrmeir, p. 388]. In summary:
$$
\begin{aligned}
\begin{pmatrix}
u_{0j} \\
u_{1j}
\end{pmatrix}
&\sim \mathcal{N}
\left(
\begin{pmatrix}
0 \\
0
\end{pmatrix},
\mathbf{T}
\right),
\qquad
\mathbf{T} =
\begin{pmatrix}
\tau_0^2 & \tau_{01} \\
\tau_{01} & \tau_1^2
\end{pmatrix}
\end{aligned}
$$
$$
\begin{aligned}
e_{ij} &\sim \mathcal{N}(0,\sigma^2) \\[6pt]
\text{Cov}(u_{0j}, e_{ij}) &= 0, \quad
\text{Cov}(u_{1j}, e_{ij}) = 0
\end{aligned}
$$

### The random intercept model
In many empirical applications of multilevel models the slope $\beta_{1j}$ is assumed to be constant across groups ($u_{1j} = 0$), leading to the *random intercept model* [@snijders, p. 45]. This model allows for baseline differences in the outcome between groups, whereas the strength of the relationship between predictors and the outcome is assumed to be constant:
$$ 
Y_{ij} = \gamma_{00} + \gamma_{10}X_{ij} + \gamma_{01}Z_j + u_{0j} + e_{ij}
$$
The random intercept model also provides a convenient framework for examining the use of *group means* of a given level-1 predictor as additional level-2 predictors. Including the group mean as a contextual variable allows the within-group regression coefficient to vary from the between-group regression coefficient [@snijders, p. 57]. This makes the model more flexible and often more realistic, as so-called *contextual effects* are frequently observed in empirical settings [@snijders, p. 27]. In such cases, the effect of an individual-level predictor differs from the effect of the average value of this predictor. Example ::: illustrates how the processes operating within groups may differ from those operating between groups.
To separate within- and between-group effects, the level-1 predictor is then often *group-mean-centered*: Instead of using $X_{ij}$ directly, the centered predictor $(X_{ij} - \bar{X}_j)$ is entered into the model. This decomposes within- and between- group effects and facilitates their interpretation [@snijders, p.58]. A random intercept model including such a decomposition can be written like this: 

$$ 
Y_{ij} = \gamma_{00} + \gamma_{10}(X_{ij} - \bar{X}_{.j}) + \gamma_{01}\bar{X}_{.j} + u_{0j} + e_{ij}
$$ {#eq-RI}
In this random intercept model with context effect, musical self-concept of student $i$ in ensemble $j$ is predicted by the sum of
$\gamma_{00}$: the average musical self-concept across all ensembles
$X_{ij} - \bar{X}_{.j}$: the group-mean centered weekly practice duration of this student 
$\bar{X}_{.j}$: the average practice duration of this student's ensemble
$u_{0j}$: a random deviation of ensemble $j$'s average MSC from the overall mean (unexplained differences between ensembles)
$e_{ij}$: a random deviation of the student's MSC from the predicted value within their ensemble  
The two regression coefficients represent the following effects:
$\gamma_{10}$: within-group effect, indicating the influence of a student's own WPD on their MSC, controlling for the ensemble context
$\gamma_{01}$: the contextual effect, indicating the influence of the ensemble's average WPD on the student's MSC

For the remainder of this thesis, the focus lies on this particular random intercept model.

### The intraclass correlation coefficient (ICC)

In the random intercept model, the variance components are given by
$$
u_{0j} \sim \mathcal{N}(0,\tau_0^2),
\qquad
e_{ij} \sim \mathcal{N}(0,\sigma^2),
\qquad
\text{Cov}(e_{ij}, u_{0j}) = 0 .
$$
From these variance components, the proportion of variability that is attributable to between-group differences can be calculated. This quantity is referred to as the *intraclass correlation coefficient* (ICC). In the empty model, the ICC is equal to the correlation between the outcomes of two randomly chosen individuals from the same group [@snijders, p. 18].
In models including predictors, the ICC is interpreted conditionally on the predictors, that is, as the correlation between two individuals from the same group who share identical predictor values (also referred to as the *residual ICC*) [@snijders, p. 52].

Formally, the ICC is defined as
$$
ICC = \frac{\tau_0^2}{\tau_0^2 + \sigma^2}
$$

The ICC is an important diagnostic metric because it indicates whether the use of a multilevel model is advantageous. If $ICC = 0,$ no between-group variance is present and individuals within the same group are not more similar to each other than to individuals from different groups (conditional on the predictors included in the model). In this case, the independence assumption of classical regression is not violated and a conventional single-level regression model is sufficient.  
Conversely, larger ICC values indicate increasing similarity within groups and thus statistical dependency of observations. Ignoring this dependency and applying a classical linear model leads to biased standard errors, confidence intervals, and hypothesis tests [@fahrmeir, p.370].

## Estimation of multilevel models {#sec-est}
In the preceding chapter, the theoretical foundation and parameters of the multilevel model were introduced. In practice, however, these parameters are unknown and only exist in the theoretical realm as ‘true’ values. The fixed effects $\gamma$ and variance components $\sigma^2$ and $\tau^2$ must therefore be estimated from observed data. Based on these estimates, inferences about the underlying population parameters are drawn.  
In multilevel modeling, statistical inference is based on estimation or approximation of various components, as illustrated in @fig-est. The reliable performance of this 'inferential machinery' depends particularly on the following elements^[in addition to correct model specification] [@elff]:

HIER GRAFIK HIN {#fig-est}

1. Estimation of fixed-effect coefficients (regression parameters)
2. Estimation of variance–covariance components of the random effects (u) and residual errors (e)
3. Selection of an appropriate approximation of the sampling distribution of the test statistic.  

Moreover, the inferential machinery itself (i.e., its formulas and underlying assumptions) may be inapt for the empirical data reality, as will be discussed in the next chapter.

## Small level-2 sample sizes in multilevel models^[In the following, I will refer to small level-2 sample sizes simply as small sample sizes, because level-1 sample sizes are usually sufficiently large and thus not problematic.]
**Einfügen: Zahlen ab wann klein**
#### Frequentist corrections for small samples
In frequentist approaches, estimation procedures of linear multilevel models are based on asymptotic theory and assume a sufficiently large sample size. In practice, this assumption is often difficult to meet, especially because estimation depends not only on the number of individual observations (Level 1), but also on the number of clusters (Level 2), which are often difficult or costly to obtain [@mcneishcoll]. Fortunately, statistics has solutions at hand for the challenges that come with this violation of the assumption. The main issues associated with small-sample multilevel models and corresponding solutions are presented below.  

Following the structure of @fig-est, we first consider the estimation of fixed effects and variance components. In MLM, these parameters can be estimated with the maximum likelihood (ML) or restricted maximum likelihood (REML) method [@snijders, p.89]. Kackar & Harville [-@kackar] showed that both ML and REML estimators of variance components are even and translation-invariant, implying that fixed effect point estimates are unbiased, independent of sample size.  
Estimation of the variance components, however, is more delicate. In ML estimation, fixed effects and variance components are estimated simultaneously, typically via iterative procedures like the Expectation Maximization (EM) mechanism [@mcneishcoll]. In this process fixed effects are effectively being treated as known when estimating variance components. Consequently, the sampling variability of the fixed-effect estimates is ignored and the loss of degrees of freedom due to their estimation is not accounted for. While these issues are not troublesome in large samples, they lead to systematic underestimation of variance components in small samples [@mcneishcoll]. 
REML fixes this issue by separating the estimation conceptually. The fixed effects are eliminated from the likelihood, and variance components are estimated solely based on residual information. Fixed effects are then estimated via generalized least squares (GLS), using the previously estimated variance components [@raudenbush, p. 410]. This leads to less downward-biased variance component estimates, while ML and REML become asymptotically equivalent as sample size increases.
The next step in the estimation scheme (@fig-est) is the model-implied variance-covariance-matrix of y (denoted $V$). It contains entries for each person and shows the marginal variance of the Y-values of one person ($\tau^2 + \sigma^2$), the covariance of outcomes in the same group ($\tau^2$), and across different groups (0, independent).  
Because the V matrix depends only on the variance components, it is also estimated more accurately with REML in small samples. The standard error depends on this matrix and on the design matrix:

$$
Var(\hat{\gamma} \mid X) = (X^TV^{-1}X)^{-1}
$$
$$
V \rightarrow \hat{V}(\hat{\theta})
$$

Even with REML, a small-sample issue results from this calculation: As $V$ uses the estimated variance components $\hat{\theta}$, these components have sampling variability and would differ each time the study is repeated. However, the variance formula (eq...) treats them as known and ignores this additional uncertainty [@mcneishcoll]. Although this variability becomes insignificantly small in large samples, it leads to underestimation of the standard errors in small samples. Accordingly, Kackar & Harville showed that the true sampling variance can be written as

$$
Var(\hat{\gamma})= Var^{REML}(\hat{\gamma}) + \text{Small Sample Bias}
$$
[@kackarcorr; @mcneishcoll].  
The Prasad-Jao-Jeske-Kackar-Harville correction provides an approximation to this bias term.  
Nevertheless, standard errors may remain slightly underestimated because the REML-based variance expression itself relies on asymptotic approximations. Kenward and Roger therefore proposed a refined approximation of the full sampling variance of the fixed effects, resulting in more accurate standard errors in small samples [@mcneishcoll].  
The standardized test statistic for inference procedures (GRAFIK) can be regarded as 'small-sample-adjusted' at this point. The final step concerns the choice of a sampling distribution for p-values and confidence intervals. In small samples, a t distribution should be used [@snijders, p. 95]. The choice of degrees of freedom is particularly important because small changes in degrees of freedom have a noticeable impact on the shape of the sampling distribution and therefore on statistical inference.  
** EINFÜGEN: ABSATZ ÜBER DFS IRGENDWO**
In multilevel models, degrees of freedom generally must be approximated, as there is no closed-form solution. For small samples, this is often done via the Kenward-Roger correction, which is based on the Satterthwaite correction [@mcneishcoll]. A simpler approximation with good properties is given by textbooks from Raudenbush & Bryk [@-raudenbush, p. 58] or Snijders & Bosker [-@snijders, p. 95]:
$$
df_{Lv1} = N_1 - r - 1, \qquad df_{Lv2} = N_2 - q - 1
$$
$$
\begin{array}{l}
N_1: \text{Level-1 sample size (total number of individuals)}\\
r: \text{Total number of predictors}\\
N_2: \text{Level-2 sample size (number of groups)}\\
q: \text{Number of predictors at level two}
\end{array}
$$

#### Fully Bayesian analysis {#sec-bayes}

Instead of relying on REML and small-sample corrections within the predominantly frequentist framework presented here, a fully Bayesian framework can be adopted to account for the additional uncertainty stemming from small sample sizes in a natural way [@raudenbush, p. 411]. A comprehensive illustration of the Bayesian framework is beyond the scope of this thesis, however, the main philosophical and practical differences to the frequentist approach will be given here:  

1. In Bayesian methods, all parameters are considered uncertain and therefore have distributions, whereas in frequentist methods parameters are assumed to have one fixed but unknown true value. Because variance components and fixed effects are represented in a joint distribution as a result of Bayesian analysis, the uncertainty of parameters is considered simultaneously for all parameters and doesn't need to be corrected for step by step as in frequentist analysis [@mcneishbay].

1. A Bayesian analysis combines prior information about parameters with the observed data, expressed by the likelihood, to obtain a posterior distribution.
This posterior distribution is the end result of Bayesian estimation. Point estimates can be taken as the posterior mean or median, and credible intervals are derived directly from percentiles from the posterior distribution [@mcneishbay]. No asymptotic standard error corrections, degrees-of-freedom adjustments, or finite-sample corrections are required.

1. Bayesian methods do not rely on large samples in the same way as frequentist methods do. Estimation of the posterior distribution is typically performed via Markov Chain Monte Carlo (MCMC) sampling. From the posterior distribution, a large number of samples is drawn to approximate its shape. In this process, the accuracy of the posterior approximation is not dependent on the sample size of the single samples, but on the number of drawn samples [@mcneishbay].

Despite all these potential advantages, a crucial point is that with smaller samples, the prior distributions are key factors, because likelihoods are relatively flat and contribute less information to the posterior distribution [@mcneish]. If informative priors based on earlier research or expert knowledge are used, this can improve performance. However, when researchers are primarily interested in their observed data or do not have prior information about the parameters, they may use noninformative, vague priors. These allow for the sampling of extreme values during MCMC estimation which in turn can lead to inflated variance parameters and posterior standard errors [@mcneishbay]. Also, recommended or software default uninformative prior distributions have proven to be more informative than intended in small sample sizes and often perform poorly [@mcneishpriors; @gelmanprior; @mcneishbay]. However, there is also evidence that Bayes estimation with noninformative priors can lead to more accurate estimation than with an ML estimator in terms of RSME in latent models [@zitzmann].
Genauer erklären, warum Bayes dann einen Vorteil hat (Stabilisierung der Varianzschätzung der between-Level-Komponente.)
DOCH NOCH ETWAS AUSFÜHRLICHER ZU MCMC ESTIMATION? -> auch für missing relevant

## Missing data in multilevel models

BEISPIEL EINFÜGEN

Missing data (i.e., incomplete data sets) are a widespread issue in empirical research and of course also applies to multilevel data, e.g., because individuals drop out of studies or forget to fill out certain items of a questionnaire. Three major concerns commonly arise from data that contain missing values:

1. The effective sample size is reduced, leading to lower efficiency in estimation (this is especially troublesome if the would-be sample size is already small)
1. Typical statistical methods are difficult to conduct, because they were designed for complete data.
1. Parameter estimation may be biased, if the missing and the observed data differ from each other systematically [@luedtke]  

Therefore, it is crucial to treat missing data appropriately. In the last three decades, this issue has received attention in psychological research, and modern methods were developed [@SG2002; @endersbook], more recently also for the more complex case of multilevel data [@luedtkeMI; @endersupdate]. This chapter discusses these methods, after giving a short introduction into different missing data mechanisms and patterns.

### Missing data mechanisms
Why data are missing can have multiple reasons, and different mechanisms may lead to different consequences in statistical inference. Rubin and Little [@littlerubin87; @rubin76] introduced a typology and theoretical framework of missing data mechanisms that describes the relationship between the observed and the missing data. 

**Missing completely at random (MCAR)**. Considering the hypothetical complete data matrix Y, $Y_{com}$ is partitioned into observed, $Y_{obs}$, and missing parts, $Y_{mis}$, and $R$ denotes the missingness^[$R$ is treated as a set of random variables that indicate for each value if it is missing or not [@SG2002].]. Missing values are considered to be MCAR if the distribution of missingness does not depend on the data [@SG2002]:
$$
P(R \mid Y_{com}) = P (R)
$$
In other words, no variable (observed or unobserved) can predict missingness and every individual in every group has the same chance of missing values [@endersbook, p. 6]
BEISPIEL

**Missing at random (MAR)**. The MAR mechanism describes the case when the probability of missingness does depend on observed data, but not on missing values [@endersbook, p.8]:
$$
P(R \mid Y_{com}) = P (R \mid Y_{obs})
$$
Missingness is therefore not random, as the name would suggest, but *conditionally random*: After controlling for the observed data, the missingness is purely random [@endersbook, p.8].
BEISPIEL

**Missing not at random (MNAR)**. If missingness depends on the observed and the missing values, this is called a missing not at random process^[The case $P(R \mid Y_{com}) = P (R \mid Y_{mis})$ is referred to as **focused MNAR** [@endersbook, p. 11].]:
$$
P(R \mid Y_{com}) = P (R \mid Y_{obs}, Y_{mis})
$$
Two individuals in the same group with identical scores in all observed variables then no longer have the same chance of missing values, because this chance depends on information that we do not have (because it lies in the missing values)[@endersbook, p.11].

BEISPIEL 
Some concluding notes:

- While these terms are also applicable to multilevel data, the situation is somewhat more complex as missing values can occur in the outcome, in level-1 predictors, in level-2 predictors or even the grouping variable (and combinations of all of these; @buuren)

- The missing data mechanism is generally not empirically testable from the observed data alone (except MCAR with Little's test); assumptions about the mechanism must therefore be theoretically justified [@endersbook, p. 14ff.].

- These missing data mechanisms are relative to the *present* data set and don't refer to $Y_{obs}$ in hypothetical repetitions of an experiment or study [@endersbook, p.13; @SG2002]. From a frequentist perspective, assumptions about the missingness mechanism must hold under repeated sampling; therefore, stricter definitions such as “*always* missing at random” have been proposed [@seaman].

- The typology is also *relative to the analysis*: Depending on the choice of the outcome and predictor variables, the underlying missingness mechanism could change [@graham09]. E.g., if the relevant predictors of missingness are observed, but omitted from the analysis model, the analysis would behave like MNAR instead of MAR conditional on the full data.


GRAFISCHES MODELL EINFÜGEN (DAGs)
IMPLICATIONS von den einzelnen Mustern?

### Methods for handling missing data
In this section, treatment methods for missing data in multilevel models will be discussed. All of the mentioned approaches assume missingness at random (MAR), or completely at random (MCAR) for listwise deletion, respectively. Frameworks for MNAR processes are not discussed in this thesis.

#### Listwise Deletion (LD)

*Listwise deletion*, a.k.a. *complete case analysis*, is one of the most widespread older approaches to missing data analysis. Cases with at least one missing value will be discarded completely, then the model is estimated using only the complete cases [@graham09]. In multilevel settings, missingness on the group level implies that all individuals in this group are excluded as well.   
Listwise deletion is still used by many researchers and remains the default in most statistical software packages [@luedtke]. There are two major disadvantages of this deletion method [@endersbook p.24]:

1. Because partial data is unused, statistical power is reduced.  
1. If the missingness mechanism is not MCAR, deletion may lead to highly biased parameter estimates.   

LD can still be adequate under some conditions [@graham09; @endersbook, p.25], but in already small samples, additional data deletion should be avoided as power is already limited [@mcneish17]. 


#### Model-based modern approaches to missing data in multilevel models
...

##### Full Information Maximum Likelihood (FIML)

In the previous chapter, maximum likelihood estimation was already briefly mentioned. This estimation principle can also be applied with missing data. In this approach, no incomplete cases are excluded and no imputations for missing values are generated. Instead, parameter estimates are obtained directly by maximizing the likelihood of the observed data [@endersbook, p. 98].    
All individuals and groups contribute their available information (that is the reason for the term "Full Information Maximum Likelihood"). If, due to missing values, no information is available about certain parameters from one individual, this person contributes only to the estimation of the remaining parameters. In mathematical terms, the missing components are integrated out of the joint likelihood function for this person, resulting in a case-specific observed-data likelihood. These are summed up across individual observations and parameter estimates are obtained by maximizing this combined likelihood [@endersbook, p. 102]. 
Because the likelihood function is based on a prespecified distributional form (often multivariate normality), the estimation procedure uses the model structure and observed data to infer plausible values for incomplete statistics under the hood. In this sense, maximum likelihood can be understood as a form of *implicit imputation*, although no missing values are explicitly filled in [@endersbook, p. 106].  

Computing FIML estimates typically requires iteration, as no closed-form solutions are available in the presence of missing data [@endersupdate]. One widely used approach is the Expectation–Maximization (EM) algorithm, which alternates between two steps. In the expectation step (E-step), the missing portions of the sufficient statistics for parameter estimation are imputed. In the maximization step (M-step), these expected sufficient statistics are substituted into the complete-data log-likelihood, and the parameter estimates are updated accordingly [@endersbook, p. 113].  

When data are MAR, ML estimation has proved to be unbiased and yields effective estimates [@mcneish17]. However, one limitation is that the inclusion of auxiliary variables that explain missingness can be difficult if these variables are not intended to appear in the substantive analysis model [@graham09]. 
Moreover, FIML software packages initially formulates the likelihood for the outcome conditional on observed predictors. Missingness in predictor variables therefore results in case deletion unless it is addressed through additional modeling assumptions. However, such modifications are not fully supported in many software packages, can be difficult to implement, and may result in unintended changes to the analysis model if the model contains manifest group means [@grundapa]. In multilevel models with contextual effects estimated in *Mplus*, this may lead to substantial bias in parameter estimates [@grundMI18].

##### Fully Bayesian Model Estimation
Missing data are treated as additional unknown quantities, analogous to model parameters. Consequently, inference is based on the joint posterior distribution of model parameters and missing values conditional on the observed data [@gelmanbook, p. 449].

The MCMC algorithm is now threefold [@endersbook, p. 190]:
First, assign starting values to all unknown quantities.
Then, repeat the following steps:
1. Update coefficients.
2. Update variance components.
3. Update imputations for missing values.

In each iteration, every step is performed conditional on the most recent draws of the other quantities. Steps one and two are equal to complete data Bayesian analysis.

Fully Bayesian estimation with missing data can be implemented using different ways of specifying the data model underlying this posterior distribution. Two major approaches are joint modeling and factored regression specifications. The imputation step (step three) is explained more thoroughly in @nte-MI.

::: {#nte-MI .callout-note icon=false}

**Imputing Missing Values**
Imputations can be understood 'predicted values plus noise' [@endersbook, p.266]. They should be reasonable guesses for missing data, while at the same time the missing-data uncertainty must be reflected in order to obtain unbiased and accurate results [@SG2002]. 
When a MAR process is assumed, the distribution of missing values is only dependent of observed data and model parameters:
$$
p(Y_{mis} \mid Y_{obs}, Y_{mis}, \theta)
=
p(Y_{mis} \mid Y_{obs}, \theta)
$$
This distribution of missing outcome values can be called a *posterior predictive distribution*, as predictions are generated based on posterior distributions of the parameters [@endersbook, p. 190]. Now it is evident why a MAR process is necessary for accurate estimates: Imputations are based on the information in the observed data, spiced with, which corresponds to the notion of MAR, that missingness is completely random, if it is conditioned on all the available data [@graham09].   
For every variable, outcome or predictor with missing values, a distribution must be available from which imputations of missing values can be drawn [@endersbook, p.192].
There a different possibilities to specify the distributions of missing values in order to impute data. For a multilevel model, two major approaches can be separated and will be sketched here: *Fully Conditional Specification* and *Joint Modeling* [@enders16].


**1. Joint Modeling**
In joint modeling, a single multivariate distribution for all variables with missing values is specified, often the multivariate normal distribution in case of continuous variables [@endersbook, p.263]. Estimation is typically implemented using Bayesian data augmentation techniques [@tanner]. Missing values are treated as unknown quantities that have a distribution. Imputations are then iteratively drawn randomly from the conditional posterior distributions of each variable given the rest, alternating with sampling the model parameters. This cycle is repeated many times until the simulated distributions stabilize [@snijders, p.137f.]. The procedure is usually carried out via a *Gibbs sampler*, a form of MCMC algorithm [@enders16]. Consequently, prior distributions must be specified for all unknown model parameters (see also @sec-bayes).
In a fully Bayesian analysis, all posterior draws of both parameters and missing values are saved, resulting in a posterior distribution for the parameters of interest. In contrast, within multiple imputation, only selected draws of the missing values are saved to create multiple complete data sets.

**2. Fully Conditional Specification**
*Fully Conditional Specification* or *Chained Equations Imputation* cycles through a sequence of univariate models for each variable with missings, conditional on the others. This approach is suitable if many ordinal or nominal variables are included in the data, as for every variable the researcher specifies a separate imputation model [@luedtke].
...

Both specifications are equal in single-level data with normally distributed values, but can differ in multilevel contexts [@enders16]. Both approaches are suitable for multilevel data structures and are implemented in common software [@enders16]
:::



#### Imputation-based methods: Multiple Imputation (MI)
While in a Bayesian analysis, missing data imputations are just a means to facilitate parameter estimation, in multiple imputation (MI) the complete datasets are saved for further analysis, whereas the Bayesian parameter inferences from the posterior distribution are discarded [@gelmanbook, p. 451]. The separation of imputation and analysis is the key distinction from model-based approaches, in which the treatment of missing data and the parameter estimation are embedded within a single estimation framework [@luedtke]. Advantages and disadvantages of each approach will be discussed in the next section.  
It is long known that a single imputation, filling each missing value with an informed guess, leads to biased point estimates and underestimated standard errors of estimates, thus to overliberal inference, because uncertainty due to missing values is not included [@rubinbook87, p.13]. Multiple imputation overcomes this limitation by generating several plausible values for each missing observations. By incorporating between-imputation variance, the additional uncertainty can be captured, as is described below in more detail [@endersbook, p.283].

Multiple imputation is carried out in three steps:

1. Create m complete data sets by multiply imputing reasonable values.
1. Perform the analysis of interest on each of the data sets.
1. Pool the m results to one final analysis result.

##### 1. Creating imputations

Where do the imputations come from?
Multiple imputation can follow different strategies to generate plausible values for the missing data. The two main frameworks are *joint imputation* and *fully conditional specification*, see @nte-MI.
A crucial point in the choice of a valid imputation model is compatibility with the focal analysis model. That is, the imputation model must reflect the key structural features of the analysis model [@grundMI18]. If it fails to do so, parameter estimates may become biased because the imputed values no longer preserve the structure of the data. Consider, for example, the random intercept model with group means (@eq-RI). In this setting, the imputation model must account for the nested data structure (i.e., random effects at the group level) and allow for different effects at the individual and the group level [@grundMI18]. Furthermore, making the imputation model 'richer' than the analysis model by adding additional effects or variables that are not part of the analysis model is beneficial for parameter estimation [@luedtke]. Such variables can serve as *auxiliary variables* and improve the performance of the missing data imputation: Auxiliary variables can help explain the missingness mechanism, thereby making the MAR assumption more plausible, or they may correlate with variables that contain missing values, which increases the precision of the imputations and reduces bias in parameter estimates [@collins].

##### 2. Analyzing the completed data sets

Researchers are now in the comfortable position to have *m* completed data sets. To each of these, the substantive analysis model of interest (e.g., the random intercept model) is then fitted. Each analysis proceeds according to the standard estimation procedure described in @sec-est, up to the computation of parameter estimates and their standard errors. Hypothesis testing is not conducted at this stage. The result of this step are *m* sets of parameter estimates and corresponding standard errors.

##### 3. Pooling the results



