# Complete simulation results for all performance measures {#sec-appB}
```{r}
#| label: setup
#| include: false
library(here)
library(dplyr)
library(kableExtra)

source(here::here("code/table_script.R"))

```


```{r}
#| results: asis
#| echo: false
#| message: false

results15_00 %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "Simulation results (N2 = 15, $\\gamma_{01}$ = 0.0)",
    col.names = c("Parameter", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
    footnote(
    general = paste(
    "Bias = average deviation from the true parameter; ",
    "Cov = empirical coverage probability; ",
    "SD = empirical standard deviation; ",
    "CIW = mean confidence/credible interval width. ",
    "MCAR = missing completely at random; MAR = missing at random. ",
    "CD = complete data; LD = listwise deletion; ",
    "MI-R = multiple imputation with Rubin's rules; ",
    "MI-a = multiple imputation with adjusted degrees of freedom; ",
    "Bayes = fully Bayesian estimation."
  ),
    threeparttable = TRUE
  ) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```

```{r}
#| results: asis
#| echo: false
#| message: false

results15_04 %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "Simulation results (N2 = 15, $\\gamma_{01}$ = 0.4)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
  footnote(general = "Abbreviations as listed in Table C.1", threeparttable = TRUE) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```

```{r}
#| results: asis
#| echo: false
#| message: false

results30_00 %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "Simulation results (N2 = 30, $\\gamma_{01}$ = 0.0)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
  footnote(general = "Abbreviations as listed in Table C.1", threeparttable = TRUE) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```

```{r}
#| results: asis
#| echo: false
#| message: false

results30_04 %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "Simulation results (N2 = 30, $\\gamma_{01}$ = 0.4)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
  footnote(general = "Abbreviations as listed in Table C.1", threeparttable = TRUE) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```

```{r}
#| results: asis
#| echo: false
#| message: false

results60_00 %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "Simulation results (N2 = 60, $\\gamma_{01}$ = 0.0)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
  footnote(general = "Abbreviations as listed in Table C.1", threeparttable = TRUE) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```

```{r}
#| results: asis
#| echo: false
#| message: false

results60_04 %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "Simulation results (N2 = 60, $\\gamma_{01}$ = 0.4)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
  footnote(general = "Abbreviations as listed in Table C.1", threeparttable = TRUE) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```



```{r}
#| results: asis
#| echo: false
#| message: false

results15_00_m %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "MCSEs of performance measures (N2 = 15, $\\gamma_{01}$ = 0.0)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
    footnote(
    general = paste(
  "All entries are Monte Carlo standard errors (MCSEs). ",
  "Abbreviations as listed in Table C.1."
  ),
    threeparttable = TRUE
  ) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```



```{r}
#| results: asis
#| echo: false
#| message: false

results15_04_m %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "MCSEs of performance measures (N2 = 15, $\\gamma_{01}$ = 0.4)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
    footnote(
    general = paste(
  "All entries are Monte Carlo standard errors (MCSEs). ",
  "Abbreviations as listed in Table C.1."
  ),
    threeparttable = TRUE
  ) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```



```{r}
#| results: asis
#| echo: false
#| message: false

results30_00_m %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "MCSEs of performance measures (N2 = 30, $\\gamma_{01}$ = 0.0)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
    footnote(
    general = paste(
  "All entries are Monte Carlo standard errors (MCSEs). ",
  "Abbreviations as listed in Table C.1."
  ),
    threeparttable = TRUE
  ) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```

```{r}
#| results: asis
#| echo: false
#| message: false

results30_04_m %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "MCSEs of performance measures (N2 = 30, $\\gamma_{01}$ = 0.4)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
    footnote(
    general = paste(
  "All entries are Monte Carlo standard errors (MCSEs). ",
  "Abbreviations as listed in Table C.1."
  ),
    threeparttable = TRUE
  ) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```

```{r}
#| results: asis
#| echo: false
#| message: false

results60_00_m %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "MCSEs of performance measures (N2 = 60, $\\gamma_{01}$ = 0.0)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
    footnote(
    general = paste(
  "All entries are Monte Carlo standard errors (MCSEs). ",
  "Abbreviations as listed in Table C.1."
  ),
    threeparttable = TRUE
  ) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```

```{r}
#| results: asis
#| echo: false
#| message: false

results60_04_m %>%
  kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    digits = 3,
    caption = "MCSEs of performance measures (N2 = 60, $\\gamma_{01}$ = 0.4)",
    col.names = c("", rep(c("Bias", "Cov", "SD", "CIW"), times = 5))
  ) %>%
  add_header_above(c(
    " " = 1,
    "CD" = 4, "LD" = 4, "MI-R" = 4, "MI-a" = 4, "Bayes" = 4
  )) %>%
  pack_rows(index = c("MCAR" = 4, "MAR" = 4), latex_align = "c") %>%
  pack_rows(index = c(
    "ICC = 0.1" = 2, "ICC = 0.3" = 2,
    "ICC = 0.1" = 2, "ICC = 0.3" = 2
  )) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "scale_down") %>%
    footnote(
    general = paste(
  "All entries are Monte Carlo standard errors (MCSEs). ",
  "Abbreviations as listed in Table C.1."
  ),
    threeparttable = TRUE
  ) %>%
  column_spec(c(5, 9, 13, 17), border_right = TRUE) %>%
  landscape() %>%
  print()
```