# Derivations of equations of the data-generating model {#sec-appA}

## Calculation of $\sigma_w^2$

The data-generating model for $W_j$ is:

$$W_j=\ a\cdot\ {\bar{X}}_j\ +e_{Wj}, \qquad e_{Wj}\ \ \sim\ N\left(0,\ {\sigma_w}^2\right)$$ {#eq-W}
The variance of $W_j$ is therefore:

$$
Var(W_j) = Var(a \cdot \bar{X}_j + e_{Wj}) 
= a^2 \cdot Var(\bar{X}_j) + Var(e_{Wj})
$$ {#eq-varw}
Substituting the formula for slope calculation $a=\ \frac{Cov(W_j,{\ \bar{X}}_j)\ }{Var({\bar{X}}_j)}$ into @eq-varw yields:
$$
\begin{aligned}
Var(W_j)
&= \frac{Cov(W_j, \bar{X}_j)^2}{Var(\bar{X}_j)^2} \cdot Var(\bar{X}_j) 
+ Var(e_{Wj}) \\
&= \frac{Cov(W_j, \bar{X}_j)^2}{Var(\bar{X}_j)} 
+ Var(e_{Wj})
\end{aligned}
$$
This term can be simplified using 
$Cov(A,B) = Corr(A,B)\cdot SD(A)\cdot SD(B)$:

$$
\begin{aligned}
Var(W_j)
&= \frac{Cov(W_j, \bar{X}_j)^2}{Var(\bar{X}_j)} + Var(e_{Wj}) \\
&= \frac{\bigl(Corr(W_j, \bar{X}_j)\cdot SD(W_j)\cdot SD(\bar{X}_j)\bigr)^2}{Var(\bar{X}_j)} 
+ Var(e_{Wj}) \\
&= \frac{Corr(W_j, \bar{X}_j)^2 \cdot Var(W_j)\cdot Var(\bar{X}_j)}{Var(\bar{X}_j)} 
+ Var(e_{Wj}) \\
&= Corr(W_j, \bar{X}_j)^2 \cdot Var(W_j) + Var(e_{Wj})
\end{aligned}
$$
Thus,

$$
\begin{aligned}
Var(W_j)
&= Corr(W_j, \bar{X}_j)^2 \cdot Var(W_j) + Var(e_{Wj}) \\
Var(e_{Wj})
&= Var(W_j) - Corr(W_j, \bar{X}_j)^2 \cdot Var(W_j) \\
&= Var(W_j)\left(1 - Corr(W_j, \bar{X}_j)^2\right)
\end{aligned}
$$
Since $Var(W_j)=1$:

$$
Var(e_{Wj}) = 1 - Corr(W_j, \bar{X}_j)^2
$$

In short notation:

$$
\sigma_w^2 = 1 - \rho_{\bar{X}W}^2
$$

## Calculation of the slope to generate $W_j$

$$
a = \frac{Cov(W_j, \bar{X}_j)}{Var(\bar{X}_j)}
$$
The variance of $\bar{X}_j$ can be derived as follows:

$$
\begin{aligned}
Var(\bar{X}_j)
&= Var\left( \frac{1}{n} \sum_{i=1}^{n} X_{ij} \right) \\
&= Var\left( \frac{1}{n} \sum_{i=1}^{n} (u_{Xj} + e_{Xij}) \right) \\
&= Var\left( \frac{1}{n} \sum_{i=1}^{n} u_{Xj} 
+ \frac{1}{n} \sum_{i=1}^{n} e_{Xij} \right) \\
&= Var\left( u_{Xj} + \frac{1}{n} \sum_{i=1}^{n} e_{Xij} \right) \\
&= Var(u_{Xj}) 
+ Var\left( \frac{1}{n} \sum_{i=1}^{n} e_{Xij} \right) \\
&= Var(u_{Xj}) 
+ \frac{1}{n^2} Var\left( \sum_{i=1}^{n} e_{Xij} \right) \\
&= Var(u_{Xj}) 
+ \frac{1}{n^2} \sum_{i=1}^{n} Var(e_{Xij}) \\
&= \tau_x^2 + \frac{n \cdot \sigma_X^2}{n^2} \\
&= \tau_x^2 + \frac{\sigma_X^2}{n}
\end{aligned}
$$ {#eq-varxbar}
where $n$ denotes the cluster size, assumed to be constant across groups. The covariance $Cov(W_j, \bar{X}_j)$ is therefore:

$$
\begin{aligned}
Cov(W_j, \bar{X}_j)
&= \rho_{\bar{X}W} \cdot SD(\bar{X}_j) \cdot SD(W_j) \\
&= \rho_{\bar{X}W} \cdot \sqrt{Var(\bar{X}_j)} \cdot \sqrt{Var(W_j)} \\
&= \rho_{\bar{X}W} \cdot \sqrt{\tau_x^2 + \frac{\sigma_X^2}{n}} \cdot 1
\end{aligned}
$$

## Variances of random components of Y {#sec-randomy}

Individual and group residual variances of $Y$ $(Var\left(u_{0j}\right) = \psi^2$ and $Var(e_{ij}) = \sigma^2$) are derived to match a prespecified residual ICC of $Y$:
$$ICC_{Y|X,W}=\ \frac{\psi^2}{\psi^2+\ \sigma^2\ }$$
Because $Var(Y)=1$ and the random components are uncorrelated with the predictors,
$$
\psi^2 + \sigma^2 = Var(\text{Residual}) = 1 - Var(\text{fixed})
$$
where $Var(\text{fixed})$ denotes the variance explained by the fixed effects.
The variance components can therefore be expressed as:

$$
Var(u_{0j}) = ICC_{Y|X,W} \cdot \bigl(1 - Var(\text{fixed})\bigr)
$$
$$
Var(e_{ij}) = (1 - ICC_{Y|X,W}) \cdot \bigl(1 - Var(\text{fixed})\bigr)
$$
$Var(\text{fixed})$ can be calculated as:
$$
Var(\text{fixed}) 
= Var\bigl( \gamma_{10} (X_{ij} - \bar{X}_{.j}) 
+ \gamma_{01} \bar{X}_{.j} 
+ \gamma_{02} W_j \bigr)
$$
The terms $(X_{ij} - \bar{X}_{j})$ and $\bar{X}_{j}$ are uncorrelated. 
$W_j$ is correlated with $\bar{X}_{j}$ but not with $X_{ij}$ (see @eq-W), and $Var(W_j)$ is set to 1, which yields:
$$
Var(\text{fixed})
= \gamma_{10}^2 \cdot Var(X_{ij} - \bar{X}_{j})
+ \gamma_{01}^2 \cdot Var(\bar{X}_{j})
+ \gamma_{02}^2
+ 2\gamma_{01}\gamma_{02} Cov(\bar{X}_{j}, W_j)
$$
Because $\gamma_{02}$ is set to zero in the present design, this term can be simplified to:
$$
Var(\text{fixed})
= \gamma_{10}^2 \cdot Var(X_{ij} - \bar{X}_{j})
+ \gamma_{01}^2 \cdot Var(\bar{X}_{j})
$$ {#eq-varfix}
The variance of $(X_{ij} - \bar{X}_{j})$ can be derived as follows:
$$
\mathrm{Var}(X_{ij} - \bar{X}_{j})
= \mathrm{Var}(X_{ij}) + \mathrm{Var}(\bar{X}_{j}) - 2 \cdot \mathrm{Cov}(X_{ij}, \bar{X}_{j})
$$
$\mathrm{Cov}(X_{ij}, \bar{X}_{j})$ can be expressed as

$$
\begin{aligned}
\mathrm{Cov}(X_{ij}, \bar{X}_{.j})
&= \mathrm{Cov}\left(X_{ij}, \frac{1}{n} \sum_{i'=1}^{n} X_{i'j} \right) \\
\end{aligned}
$$
where $i'$ may be the same or a different index than $i$.
Using the decomposition of $X_{ij}$ introduced in @sec-dgm, $X_{ij} = u_{Xj} + e_{Xij}$, the covariance term can be rewritten and expanded as

$$
\begin{aligned}
\mathrm{Cov}(X_{ij}, \bar{X}_{j})
&= \mathrm{Cov}\left(u_{Xj} + e_{Xij}, \frac{1}{n} \sum_{i'=1}^{n} (u_{Xj} + e_{Xi'j}) \right) \\
&= \mathrm{Cov}\left(u_{Xj} + e_{Xij},\ u_{Xj} + \frac{1}{n} \sum_{i'=1}^{n} e_{Xi'j} \right) \\
&= \mathrm{Cov}(u_{Xj}, u_{Xj})
+ \mathrm{Cov}\left(u_{Xj}, \frac{1}{n} \sum_{i'=1}^{n} e_{Xi'j}\right) \\
&\quad + \mathrm{Cov}(e_{Xij}, u_{Xj})
+ \mathrm{Cov}\left(e_{Xij}, \frac{1}{n} \sum_{i'=1}^{n} e_{Xi'j}\right)
\end{aligned}
$$
Because of uncorrelatedness between $u_{Xj}$ and $e_{Xij}$, the second and third term are zero; furthermore, $\mathrm{Cov}\left(e_{Xij}, \frac{1}{n} \sum_{i'=1}^{n} e_{Xi'j}\right)  = \frac{1}{n} \sum_{i'=1}^{n} \mathrm{Cov}(e_{Xij}, e_{Xi'j})$.  
As $\mathrm{Cov}(e_{Xij}, e_{Xi'j}) = \mathrm{Var}(e_{Xij})$ if $i=i'$ and zero otherwise, $\frac{1}{n} \sum_{i'=1}^{n} \mathrm{Cov}(e_{Xij}, e_{Xi'j}) = \frac{1}{n}\mathrm{Var}(e_{Xij})$.

\noindent Overall, the covariance now simplifies to
$$
\begin{aligned}
\mathrm{Cov}(X_{ij}, \bar{X}_{j})
&= \mathrm{Var}(u_{Xj}) + \frac{1}{n}\mathrm{Var}(e_{Xij})\\
&= \tau_x^2 + \frac{\sigma_X^2}{n}\\
&= \mathrm{Var}(\bar{X_j})
\end{aligned}
$$
Returning to $\mathrm{Var}(X_{ij} - \bar{X}_{j})$, this simplifies to:
$$
\begin{aligned}
\mathrm{Var}(X_{ij} - \bar{X}_{j})
&= \mathrm{Var}(X_{ij}) + \mathrm{Var}(\bar{X}_{j}) - 2 \cdot \mathrm{Cov}(X_{ij}, \bar{X}_{j})\\
&= \mathrm{Var}(X_{ij}) + \mathrm{Var}(\bar{X}_{j}) - 2 \cdot \mathrm{Var}(\bar{X}_{j})\\
&= \mathrm{Var}(X_{ij}) - \mathrm{Var}(\bar{X}_{j})\\
&= (\tau_x^2 + \sigma_X^2) -(\tau_x^2 + \frac{\sigma_X^2}{n})\\
&= \sigma_X^2 -\frac{\sigma_X^2}{n}
\end{aligned}
$$
Inserting the derived terms into @eq-varfix$, Var(\text{fixed})$ can be therefore calculated as
$$
Var(\text{fixed})
= \gamma_{10}^2 \left(\sigma_X^2 - \frac{\sigma_X^2}{n}\right)
+ \gamma_{01}^2 \left(\tau_x^2 + \frac{\sigma_X^2}{n}\right).
$$
The variances of the random components can thus be calculated like this:
 
$$ 
\begin{aligned}
\psi^2 
= ICC_{Y|X,W} \cdot 
\left(
1 -
\left[
\gamma_{10}^2\left(\sigma_X^2 - \frac{\sigma_X^2}{n}\right)
+
\gamma_{01}^2\left(\tau_x^2 + \frac{\sigma_X^2}{n}\right)
\right]
\right)
\end{aligned}
$$

$$
\begin{aligned}
\sigma^2 
= (1 - ICC_{Y|X,W}) \cdot
\left(
1 -
\left[
\gamma_{10}^2\left(\sigma_X^2 - \frac{\sigma_X^2}{n}\right)
+
\gamma_{01}^2\left(\tau_x^2 + \frac{\sigma_X^2}{n}\right)
\right]
\right)
\end{aligned}
$$